[package]
name = "dos-actors"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["clients/*"]

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
quote = "1.0.14"
syn = "1.0.85"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
windloads = { path = "clients/windloads", optional = true }

[dev-dependencies]
anyhow = "1.0.52"
complot = "0.3.2"
rand = "0.8.4"
rand_distr = "0.4.2"
