[package]
name = "dos-actors"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
quote = "1.0.14"
syn = "1.0.85"
thiserror = "1.0.30"
log = "0.4.14"
paste = "1.0.6"
geotrans = "0.2"
async-trait = "0.1.52"
nalgebra = "0.30.1"
skyangle = "0.1.0"
anyhow = "1.0.56"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "sync"] }
parse-monitors = { path = "../parse-monitors", optional = true }# git = "https://github.com/rconan/parse-monitors.git", branch = "main", optional = true}
fem = { version = "0.2", package = "gmt-fem" , optional = true}
mount-ctrl = { version = "0.2" , optional = true}
m1-ctrl = { git = "https://github.com/rconan/m1-ctrl.git", branch = "hf_design", optional = true }
arrow = { version = "10.0.0", optional = true }
parquet = { version = "10.0.0", optional = true }
rand = { version = "0.8.4", optional = true }
rand_distr = { version = "0.4.3", optional = true }
fsm = { git = "https://github.com/rodrigo-romano/m2-ctrl-code.git", branch = "2022-03-update", optional = true }
crseo = { path = "../crseo/", optional = true }
serde-pickle = { version = "1.1.0", optional = true }
lom = { path = "../gmt-lom", package = "gmt-lom", features = ["apache"], optional = true }

[patch.crates-io]
fem = { path = "../fem", package = "gmt-fem" }

[features]
windloads = ["parse-monitors"]
apache-arrow = ["arrow", "parquet"]
noise = ["rand", "rand_distr"]
sampler = []
feedback = []

[dev-dependencies]
anyhow = "1.0.52"
complot = "0.3.2"
rand = "0.8.4"
rand_distr = "0.4.3"
simple_logger = "2.1.0"
welch-sde = { path = "../welch-sde" }
structopt = "0.3.26"

[[test]]
name = "zero_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]
[[test]]
name = "setpoint_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]

[[test]]
name = "zero_mount-m1"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl"]
[[test]]
name = "setpoint_mount-m1"
required-features = ["fem", "mount-ctrl", "m1-ctrl"]

[[test]]
name = "zero_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl", "fsm"]
[[test]]
name = "setpoint_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "fsm"]

[[test]]
name = "zero_mount-m1-m2-tt"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl", "fsm"]