[package]
name = "dos-actors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
parking_lot = "0.11.2"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }

[dev-dependencies]
anyhow = "1.0.52"
